# Site
repository: https://github.com/golosniyd/
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dmitriy Golosniy
title: DevOps Engineer
email: dmitriy.golosniy@ya.ru
website: https://golosniyd.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  golosniyd
telegram_username: elmcy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Dmitriy and I'm a DevOps Engineer. 
  As well as administrating systems I also have experience making software and web apps. 
  I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Kubernetes</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
  
  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - CI/CD Tools: 
          - <mark>CircleCI</mark> <mark>ArgoCD</mark> <mark>Azure DevOps Pipelines</mark> 
      - Databases: 
          - <mark>PostgreSQL</mark>
      - Container Orhchestration: 
          - <mark>Docker</mark> <mark>Kubernetes</mark> <mark>Helm</mark>
      - Cloud Providers: 
          - <mark>AWS</mark>
      - Configuration Management: 
          - <mark>Ansible</mark>
      - Infrastructure Provisioning:
          - <mark>Terraform</mark>    
      - Source Control: 
          - <mark>Git</mark> <mark>Bitbucket</mark>
      - Analytics and Monitoring: 
          - <mark>Elastic ELK stack</mark> <mark>Graylog</mark>
      - Programming Languages: 
          - <mark>Python</mark> <mark>Java</mark>  
      - Testing: 
          - <mark>Jmeter</mark> <mark>Selenium</mark>
      - Operating Systems:
          - <mark>Windows</mark> <mark>Ubuntu</mark>  
      - Web Servers:
          - <mark>Tomcat</mark> <mark>Nginx</mark>
      - Others: 
          - <mark>Atlassian Jira</mark> <mark>Kafka</mark>


  # - title: Certificates # Title for the section
  #   layout: list
  #   content:
  #     - layout: left
  #       title: AWS
  #       sub_title: AWS Certified Solutions Architect - Associate
  #       caption: 2019 - Present

  #     - layout: left
  #       title: Kubernetes
  #       sub_title: Certified Kubernetes Administrator
  #       caption: 2022 - Present  

  #     - layout: left
  #       title: Docker
  #       sub_title: Docker Certified Associate
  #       caption: 2022 - Present

  #     - layout: left
  #       title: Linux
  #       sub_title: Linux Certified System Administrator
  #       caption: 2022 - Present  

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sperasoft Studio
        link: https://sperasoft.com/
        # link_text: boringcompany.com
        sub_title: Middle II Quality Assurance
        caption: November 2019 - Present
        description: | # this will include new lines to allow paragraphs
            Started as QA Engineer and moved to DevOps Engineer. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Volgograd State Agrarian University
        caption: 2009 - 2013
        sub_title: Engineer of road transport systems
        description: About education
        
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Guitar
      - Gaming
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)


# Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
