# Site
repository: https://github.com/golosniyd/
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Дмитрий Голосный
title: DevOps Engineer
email: dmitriy.golosniy@ya.ru
website: https://golosniyd.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  golosniyd
telegram_username: elmcy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Обо мне
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Привет, меня зовут Дмитрий и я работаю DevOps/QA инженером.
  В рамках своей профессиональной деятельности я занимаюсь администрированием систем, разработкой скриптов и поддержкой инфраструктуры.
  В дополнение к вышесказанному, имею начальные навыки в работе с облачными сервисами, разработки программного обеспечения и веб-технологиях. 
  Полный технологический стек представлен ниже


content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
  
  - title: Стек технологий с которыми я работаю или работал # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - CI/CD Tools: 
          - <mark>CircleCI</mark> <mark>ArgoCD</mark>
      - Databases: 
          - <mark>PostgreSQL</mark>
      - Container Orhchestration: 
          - <mark>Docker</mark> <mark>Kubernetes</mark> <mark>Helm</mark>
      - Cloud Providers: 
          - <mark>AWS</mark>
      - Configuration Management: 
          - <mark>Ansible</mark>
      - Infrastructure Provisioning:
          - <mark>Terraform</mark>    
      - Source Control: 
          - <mark>Git</mark>
      - Programming Languages: 
          - <mark>Python</mark> <mark>Go</mark>  
      - Testing: 
          - <mark>Jmeter</mark> <mark>Selenium</mark>
      - Operating Systems:
          - <mark>Windows</mark> <mark>Ubuntu</mark> 
      - Web Servers:
          - <mark>Tomcat</mark> <mark>Nginx</mark>
      - Others: 
          - <mark>Atlassian Jira</mark> <mark>Kafka</mark> <mark>ELK & EFK</mark>


  # - title: Certificates # Title for the section
  #   layout: list
  #   content:
  #     - layout: left
  #       title: AWS
  #       sub_title: AWS Certified Solutions Architect - Associate
  #       caption: 2019 - Present

  #     - layout: left
  #       title: Kubernetes
  #       sub_title: Certified Kubernetes Administrator
  #       caption: 2022 - Present  

  #     - layout: left
  #       title: Docker
  #       sub_title: Docker Certified Associate
  #       caption: 2022 - Present

  #     - layout: left
  #       title: Linux
  #       sub_title: Linux Certified System Administrator
  #       caption: 2022 - Present  

  - title: Опыт # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sperasoft Studio
        link: https://sperasoft.com/
        # link_text: boringcompany.com
        sub_title: QA M2/DevOps Engineer
        caption: Ноябрь 2019 - По настоящее время
        description: | # this will include new lines to allow paragraphs
            Начал работу как QA Engineer в Sperasoft Studio с 2019 года. Далее, начал выполнять работу как DevOps Engineer.
            Моя зона ответственности на проекте включает следующее:  
            DevOps:
            - администрирование пяти тестовых стендов (Ubuntu)
            - настройка и поддержка мониторинга стендов (NodeExporter, Prometheus, Grafana)
            - написание скриптов автоматизации (Bash, Python, Go)
            - создание и поддержка однонодового Kubernetes кластера (+Helm)
            - описание облачной инфраструктуры с помощью Terraform (AWS)
            - поддержка инфраструктуры проекта (Docker, Tomcat, Kafka, Jira, ELK)
            - определение и настройка политики резервного копирования (PostgreSQL)
            QA:
            - тестирование ERP системы (Тестирование требований, Смоук, Функциональное, Регрессионное)
            - написание проектной документации
            - нагрузочное тестирование (Jmeter)
            - RnD активности (e.g. Puppiteer)
            - фикс минорных багов в коде проекта (Java)

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Волгоградский государственный аграрный университет
        caption: 2009 - 2013
        sub_title: Инженерно-технологический факультет, Механизация сельского хозяйства
        # description: About education
        
  - title: О моих увлечениях
    layout: text
    content: | # this will include new lines to allow paragraphs
      Помимо моего интереса к сетям и программированию я увлекаюсь гитарой и видеоиграми.


# Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
